const actions = {
  RESET_COURSE: "RESET_COURSE",
  ADDCOURSES: "ADDCOURSES",
  ADDCOURSES_ERROR: "ADDCOURSES_ERROR",
  GET_COURSE: "GET_COURSE",
  GET_COURSE_ERROR: "GET_COURSE_ERROR",
};

export default actions;
